### ISSUE TITLE
Geoduck Transcriptome

### ISSUE THREAD

**Issue by sr320** [laurahspencer/546-Bioinformatics#2]
available [here](https://github.com/sr320/paper-pano-go/raw/master/data-results/Geoduck-transcriptome-v3.fa.zip)

(zipped fasta)

**Comment by laurahspencer** [comment]
I'm having difficulty with the transcriptome file:
- Tried to decompress the file via GUI directory, and the resulting file was another .zip folder with the .cpgz file type. [Google](http://osxdaily.com/2013/02/13/open-zip-cpgz-file/) told me that .cpgz is created if a file is corrupted or only partially downloaded. I tried downloading & unzipping again, to no avail.  
- Another suggestion was to unzip via the terminal using `unzip`. I tried to use that, but get an error that the .zip file does not exist. See my [Jupyter notebook](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/Jupyter/Geoduck%20Annotation%20Project.ipynb) for details @ line 24 onwards. 

Any suggestions would be most appreciated! Thanks!

**Comment by sr320** [comment]
If you have a Mac it should be simple to uncompress? see video
![screen capture on 2016-10-20 at 19-19-18](https://cloud.githubusercontent.com/assets/4442039/19584545/2c1a1a26-96fa-11e6-8ba5-c05626ace2fe.gif)

Your link to your notebook does not go work

**Comment by sr320** [comment]
I found your notebook..

that last command should not be 
`!unzip ../Geoduck-transcriptome-v3.fa.zip`

but rather 

`!unzip Geoduck-transcriptome-v3.fa.zip`

**Comment by laurahspencer** [comment]
Good to know! I'll have to brush up on the relative path concept ...
However, I still get an error; this one is different:

![Unzip error](https://github.com/laurahspencer/546-Bioinformatics/blob/master/2016-10_Geo-Ann-Project/Jupyter-Notebooks/Notebook-Images/Transcript-unzip-issue.png?raw=true) 

I just downloaded the file as you suggested in the gif (and _not_ from the Jupyter command line using `curl`), and this time `unzip` worked! Strange! Thanks again for your help!
