### ISSUE TITLE
Data file for annotated p. generosa transcriptome

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/546-Bioinformatics#4]
@sr320 I'm at the point where I want to merge the transcriptome annotations with my data file, and I've been poking around your [paper.pano.go repo](https://github.com/sr320/paper-pano-go) as well as your blog to find the appropriate file to use.  Looks like either the [Geoduck-transcriptome-v3annotated.fa.zip](https://github.com/sr320/paper-pano-go/blob/master/data-results/Geoduck-transcriptome-v3annotated.fa.zip) file or [Geoduck-transcriptome-v3_bigtale_final](https://github.com/sr320/paper-pano-go/blob/master/data-results/Geoduck-transcriptome_v3_bigtable_final.csv.zip) could be the ticket, but I wanted to confirm with you.  

Also, do you have fifteen minutes this afternoon to chat about this project?  I'm struggling a bit on the next steps - also I've checked out your [March 31st blot post](http://onsnetwork.org/halfshell/2016/03/31/getting-back-on-tracks/), in which you start to "add tracks" to the geoduck genome, and I'm interested to hear more about this approach.

**Comment by sr320** [comment]
Does it make sense to do a hangout today so I can show you what I have done and how to do it? See where you are in the process?

**Comment by laurahspencer** [comment]
That would be very helpful, if you have time! I'm available from ~1:40 - 3:20 today, and after 4:30pm. Either of those windows work?  
@sr320

**Comment by laurahspencer** [comment]
Update: I'm free from ~1:40 - 3pm, and after 4:30

**Comment by sr320** [comment]
I have a call at 2, will ping you when I am done if before 3...

**Comment by laurahspencer** [comment]
Sounds good. Also, if 1:30 works for you I can make that happen.

**Comment by laurahspencer** [comment]
@sr320 if you happen to be available after 3:20pm today it would be helpful to do a hangout. If not today, tomorrow morning also works. Thanks!
Laura

**Comment by sr320** [comment]
Sure- let's do 3:30 today
