### ISSUE TITLE
Geoduck RNASeq data, and username for genefish computer

### ISSUE THREAD

**Issue by laurahspencer** [laurahspencer/546-Bioinformatics#5]
@sr320 
1.  Could you point me to an appropriate RNASeq data file for geoduck that I can use in my project?
2. May I please have a username/pw to access the genefish computer? Thanks!

**Comment by sr320** [comment]
fastq files:
Two Paired-end libraries. One female gonad, one male gonad....

be in touch re computer access.

   -
   http://owl.fish.washington.edu/halfshell/bu-data-genomic/tentacle/Geoduck_v3/Geo_Pool_F_GGCTAC_L006_R2_001_val_1.fq
   -
   http://owl.fish.washington.edu/halfshell/bu-data-genomic/tentacle/Geoduck_v3/Geo_Pool_F_GGCTAC_L006_R1_001_val_2.fq
   -
   http://owl.fish.washington.edu/halfshell/bu-data-genomic/tentacle/Geoduck_v3/Geo_Pool_M_CTTGTA_L006_R2_001_val_1.fq
   -
   http://owl.fish.washington.edu/halfshell/bu-data-genomic/tentacle/Geoduck_v3/Geo_Pool_M_CTTGTA_L006_R1_001_val_2.fq

https://github.com/sr320/paper-pano-go/wiki/Quality-trim-output#female
